### ISSUE TITLE
left of '.data' must have class/struct/union

### ISSUE THREAD

**Issue by ispysoftware** [radioman/WebRtc.NET#10]
Very cool project -  I'm getting errors building the main dll file (in visual studio 2015), any ideas?

decltype(std::declval<C>().data()

Error	C2228	left of '.data' must have class/struct/union	WebRtc.NET	D:\Projects\WebRtc.NET-master\WebRtc.NET\include\webrtc\base\type_traits.h	27

**Comment by ZoolWay** [comment]
Are there more errors? The type_traits errors usually go away when fixing the real errors - at least for my Visual Studio 2015 U3

**Comment by ispysoftware** [comment]
Updating visual studio to update 3 resolved the issue. Thanks for the response.
