### ISSUE TITLE
X64 Build fails - Cannot open include file: 'webrtc/base/win32.h': No such file or directory

### ISSUE THREAD

**Issue by rlongre** [radioman/WebRtc.NET#11]
Thanks for adding the 64 bit build! I'm starting to prototype with it but hit these build errors on a fresh clone...

1>------ Build started: Project: WebRtc.NET.Utils, Configuration: Debug Any CPU ------
1>  WebRtc.NET.Utils -> \WebRtc.NET.Utils\bin\Debug\WebRtc.NET.Utils.dll
2>------ Build started: Project: WebRtc.NET, Configuration: Debug x64 ------
2>  stdafx.cpp
2>\webrtc.net\stdafx.h(9): fatal error C1083: Cannot open include file: 'webrtc/base/win32.h': No such file or directory
3>------ Build started: Project: WebRtc.NET.AppLib, Configuration: Debug Any CPU ------
3>\WebRtc.NET.AppLib\WebRTCServer.cs(286,16,286,32): error CS0246: The type or namespace name 'ManagedConductor' could not be found (are you missing a using directive or an assembly reference?)
3>\WebRtc.NET.AppLib\WebRTCServer.cs(18,29,18,45): error CS0246: The type or namespace name 'ManagedConductor' could not be found (are you missing a using directive or an assembly reference?)
3>\WebRtc.NET.AppLib\MainForm.cs(51,18,51,34): error CS0246: The type or namespace name 'TurboJpegEncoder' could not be found (are you missing a using directive or an assembly reference?)
4>------ Build started: Project: WebRtc.NET.App, Configuration: Debug x64 ------
4>CSC : error CS0006: Metadata file '\WebRtc.NET.AppLib\bin\Debug\WebRtc.NET.AppLib.dll' could not be found
========== Build: 1 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========

**Comment by rlongre** [comment]
Seems like the 64-bit WebRtc.NET project configuration is missing some include directories and pre-processor definitions.

**Comment by rlongre** [comment]
The above is for the 64-bit debug build. Below are the errors for the 64-bit release build...

1>------ Build started: Project: WebRtc.NET, Configuration: Release x64 ------
1>  Generating code
1>  73 of 2536 functions ( 2.9%) were compiled, the rest were copied from previous compilation.
1>    0 functions were new in current compilation
1>    61 functions had inline decision re-evaluated but remain unchanged
1>  Finished generating code
1>libcpmt.lib(wlocale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(wlocale.obj) : error LNK2005: "public: int __cdecl std::ios_base::flags(void)const " (?flags@ios_base@std@@QEBAHXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(wlocale.obj) : error LNK2005: "public: __int64 __cdecl std::ios_base::width(__int64)" (?width@ios_base@std@@QEAA_J_J@Z) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(wlocale.obj) : error LNK2005: "public: __int64 __cdecl std::ios_base::width(void)const " (?width@ios_base@std@@QEBA_JXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(xlock.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(xdateord.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(locale0.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(locale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(locale.obj) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Pninc(void)" (?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(locale.obj) : error LNK2005: "public: int __cdecl std::ios_base::flags(void)const " (?flags@ios_base@std@@QEBAHXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(locale.obj) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::gptr(void)const " (?gptr@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEBAPEADXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(locale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(locale.obj) : error LNK2005: "public: __int64 __cdecl std::ios_base::width(__int64)" (?width@ios_base@std@@QEAA_J_J@Z) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(locale.obj) : error LNK2005: "public: __int64 __cdecl std::ios_base::width(void)const " (?width@ios_base@std@@QEBA_JXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(StlCompareStringA.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(StlLCMapStringA.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(winapinls.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(StlCompareStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(StlLCMapStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(iosptrs.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(xthrow.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(xthrow.obj) : error LNK2005: "void __cdecl std::_Xbad_alloc(void)" (?_Xbad_alloc@std@@YAXXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(xthrow.obj) : error LNK2005: "void __cdecl std::_Xbad_function_call(void)" (?_Xbad_function_call@std@@YAXXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(xthrow.obj) : error LNK2005: "void __cdecl std::_Xlength_error(char const *)" (?_Xlength_error@std@@YAXPEBD@Z) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(xthrow.obj) : error LNK2005: "void __cdecl std::_Xout_of_range(char const *)" (?_Xout_of_range@std@@YAXPEBD@Z) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(xlocale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>libcpmt.lib(xlocale.obj) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Pninc(void)" (?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(xlocale.obj) : error LNK2005: "public: int __cdecl std::ios_base::flags(void)const " (?flags@ios_base@std@@QEBAHXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(xlocale.obj) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::gptr(void)const " (?gptr@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEBAPEADXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(xlocale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(xlocale.obj) : error LNK2005: "public: __int64 __cdecl std::ios_base::width(__int64)" (?width@ios_base@std@@QEAA_J_J@Z) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(xlocale.obj) : error LNK2005: "public: __int64 __cdecl std::ios_base::width(void)const " (?width@ios_base@std@@QEBA_JXZ) already defined in msvcprt.lib(MSVCP140.dll)
1>libcpmt.lib(winapisupp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in conductor.obj
1>Release_x64\WebRtc.NET.dll : fatal error LNK1169: one or more multiply defined symbols found
2>------ Build started: Project: WebRtc.NET.AppLib, Configuration: Release Any CPU ------
2>CSC : error CS0006: Metadata file '\WebRtc.NET\Release_x64\WebRtc.NET.dll' could not be found
3>------ Build started: Project: WebRtc.NET.App, Configuration: Release x64 ------
3>CSC : error CS0006: Metadata file '\WebRtc.NET.AppLib\bin\Release\WebRtc.NET.AppLib.dll' could not be found
========== Build: 0 succeeded, 3 failed, 1 up-to-date, 0 skipped ==========

**Comment by km147** [comment]
Just to confirm that we had the same problem!

**Comment by rlongre** [comment]
Commit 10df3c8 resolves build issues for the 64-bit Release build. Thank you! This removes any blocks for for me for prototyping. The debug build still has issues and will be needed if this prototype works out.

**Comment by radioman** [comment]
i haven't made debug build yet, i wonder if it's really useful? I found myself using only release dll anyway
