### ISSUE TITLE
WebRTC native build, gn arguments

### ISSUE THREAD

**Issue by ZoolWay** [radioman/WebRtc.NET#12]
Hi!
With which `gn` options do you do the native build? I tried to reproduce the libraries but those generated by this do not seem to be compatible (ignoring your x64 approach at this moment):

```
gn gen out/Debug --args="target_cpu=\"x86\" is_component_build=true"
```

I get a boringssl.dll.lib (instead of boringssl.lib) and a protobuf_lite.dll.lib (instead of protobuf_lite.lib) and when linking against those I still got some unresolved externals. Might be mainly the libvpx intrinsics because I dont get libvpx_intrinsics_*.lib files after the compilation completed, just libvpx.lib and libvpx_yasm.lib. So I guess there most be at least one more flag to control the libvpx build.

Any hints?

**Comment by radioman** [comment]
`gn gen out/DebugX86 --ide="vs2015" --args="is_debug=true target_cpu=\"x86\" is_component_build=false symbol_level=0"`

and gn build config has some errors, you need to manualy link libvpx_intrinsics_ projects from visual studio, it's a pain...

**Comment by ZoolWay** [comment]
Thanks for sharing!

With `is_component_build=false` I get errors that the runtime library mismatches, looks like the libs are MTd_StaticDebug while my assembly is MDd_DynamicDebug (like your `WebRtc.NET`).

Are you compiling with ninja or the `all.sln` generated?

When I compile the intrinsics with the all.sln, just object files get generated, not the lib files (exactly like ninja).

**Comment by ZoolWay** [comment]
Ah, as you said, I need to **link** the intrinsics projects and will get the libs. Other than that, the solutions feels a bit useless.

**Comment by radioman** [comment]
and yes their runtime config is broken too, i've manualy fixed config in [build/config/win/BUILD.gn](https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/include/build/config/win/BUILD.gn#L271)
