### ISSUE TITLE
AudioRenderer OnData never called

### ISSUE THREAD

**Issue by km147** [radioman/WebRtc.NET#13]
Hi,

I'm experiencing an issue where remote audio sent from the page the AudioRenderer interface results in the OnData function never actually being called. As a result I cannot get the audio data from WebRTC. Am I correct in expecting this function to work similarly to the VideoRenderer OnFrame function?

Perhaps this is an issue with WebRTC itself and possibly related to this?: https://bugs.chromium.org/p/webrtc/issues/detail?id=5161

The article suggests this has now been implemented but I cannot get audio data.

Can you confirm this issue?

Thank you for all your efforts on this, it is much appreciated!

**Comment by radioman** [comment]
yes, the function isnt called, i did not try this on the latest version yet, maybe they fixed it maybe not, dunno

**Comment by radioman** [comment]
p.s. just tested latest version, zip, doesnt work

**Comment by km147** [comment]
OK thanks for confirming - we've put the pressure on Mr cheung.w...@gmail.com for why he says it does give meaningfull data!

**Comment by km147** [comment]
Can confirm latest release provides meaningful data. Thank you very much and greatly appreciated.

**Comment by radioman** [comment]
do you you mean latest webrtc commit on https://chromium.googlesource.com/external/webrtc.git/+log/master ?

**Comment by km147** [comment]
We got success with the latest commit (Downloaded a week ago) togther with your update last weekend. It took us from Monday to Friday to get it working not entirly sure we can recall all the changes we have made too but will confirm more info here on Monday!

**Comment by km147** [comment]
It works with your latest commit simply by enabling audio in conductor.cc and in the rtc_main.js client code. Now AudioRenderer::OnData function is called. Using windows 10 64-bit

**Comment by radioman** [comment]
hm, doesnt work for me ;/
