### ISSUE TITLE
Unable to run Application

### ISSUE THREAD

**Issue by chris774** [radioman/WebRtc.NET#14]
I've downloade the v6 release and when I try to run the sample app I get the following error

Additional information: Could not load file or assembly 'WebRtc.NET.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)

WebRtc.net is being built for Win32 while the other projects are set to x86.

Any idea what's wrong ?

**Comment by radioman** [comment]
works fine, builds fine, vs2015.3

**Comment by chris774** [comment]
I'm using vs2015.3 as well and running on a Windows 7 x64 machine, it compiles but does not run. I'm going to try it on vs2017RC, using a Windows 10 machine.

**Comment by radioman** [comment]
hm, can you check the dll with http://www.dependencywalker.com ? I'm on win10x64, but it should work everywhere if you distribute ms crt dlls

**Comment by radioman** [comment]
p.s. added crt dlls

**Comment by chris774** [comment]
On windows 10 it compiles and runs no problem. And cool thanks, I'll try again on Windows 7 too

**Comment by LeeHM** [comment]
I'm using vs2015 win7x64 but not build. error "webrtc/base/win32.h no such dir or file" and namespace notfound.

**Comment by imzaheermehmood** [comment]
I tried to compile this project with source code and with only libraries. project with source has a lot of errors while binaries have unimplemented methods. Is there anything that I should keep in mind to run this successfully. Thanks

**Comment by radioman** [comment]
no errors, i do not commit uncompilable code, don't forget to extract libs

**Comment by EbramSamy** [comment]
I was testing on windows 7 X86 also and I get the same error message any advice ?!

**Comment by EbramSamy** [comment]
after enable native debugging I got these messages : 
         
              'WebRtc.NET.Demo.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. Cannot find or open the PDB file.
The thread 0x1240 has exited with code 0 (0x0).
'WebRtc.NET.Demo.exe' (Win32): Loaded 'C:\git\WebRtc.NET\WebRtc.NET.Demo\bin\x86\Debug\WebRtc.NET.dll'. Symbols loaded.
'WebRtc.NET.Demo.exe' (Win32): Unloaded 'C:\git\WebRtc.NET\WebRtc.NET.Demo\bin\x86\Debug\WebRtc.NET.dll'
Exception thrown at 0x75E0B760 in WebRtc.NET.Demo.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x0022CBE4.
Exception thrown at 0x75E0B760 in WebRtc.NET.Demo.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x75E0B760 in WebRtc.NET.Demo.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x75E0B760 in WebRtc.NET.Demo.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x75E0B760 in WebRtc.NET.Demo.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x75E0B760 in WebRtc.NET.Demo.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown: 'System.BadImageFormatException' in WebRtc.NET.Demo.exe
Exception thrown at 0x77C85715 (ntdll.dll) in WebRtc.NET.Demo.exe: 0xC0000005: Access violation reading location 0x8BD845AD.
The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.
Exception thrown at 0x77C85715 (ntdll.dll) in WebRtc.NET.Demo.exe: 0xC0000005: Access violation reading location 0x00000024.
The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.
Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in 'C:\git\WebRtc.NET\WebRtc.NET.Demo\bin\x86\Debug\WebRtc.NET.Demo.exe'.
Additional information: The runtime has encountered a fatal error. The address of the error was at 0x6b06a49b, on thread 0x13d0. The error code is 0x80131506. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.

Exception thrown at 0x6ADAA54E (clr.dll) in WebRtc.NET.Demo.exe: 0xC0000005: Access violation reading location 0x00000014.
The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.
Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in 'C:\git\WebRtc.NET\WebRtc.NET.Demo\bin\x86\Debug\WebRtc.NET.Demo.exe'.
Additional information: The runtime has encountered a fatal error. The address of the error was at 0x6adaa54e, on thread 0x13d0. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.

Exception thrown at 0x6ADAA54E (clr.dll) in WebRtc.NET.Demo.exe: 0xC0000005: Access violation reading location 0x00000014.
The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.
Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in 'C:\git\WebRtc.NET\WebRtc.NET.Demo\bin\x86\Debug\WebRtc.NET.Demo.exe'.
Additional information: The runtime has encountered a fatal error. The address of the error was at 0x6adaa54e, on thread 0x13d0. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.

The program '[5656] WebRtc.NET.Demo.exe' has exited with code 0 (0x0).

**Comment by EbramSamy** [comment]
I found these answers about EEFileLoadException for Managed C++:

http://stackoverflow.com/questions/93770/eefileloadexception-when-using-c-sharp-classes-in-cwin32-app


http://stackoverflow.com/questions/16796335/eefileloadexception-when-loading-c-dll-in-managed-dll

**Comment by radioman** [comment]
check https://github.com/radioman/WebRtc.NET/issues/43

**Comment by EbramSamy** [comment]
I think it a different issue and what exactly missing and need to be up to date because some answers say "That strongly suggests you have a 32/64 confusion.  Are you quite sure that your C# application is compiled for AnyCPU?  It's quite possible to compile a C# application for Win32, in which case it will be a 32-bit process even on a 64-bit system."
