### ISSUE TITLE
Increase Screen Width

### ISSUE THREAD

**Issue by EbramSamy** [radioman/WebRtc.NET#15]
Now I am trying to increase screen width and screen height but I got green image
const int screenWidth = 640;
 const int screenHeight = 360;
to 
const int screenWidth = 1920;
const int screenHeight = 1080;

**Comment by sgilani** [comment]
same problem here, any ideas?

**Comment by radioman** [comment]
https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/src/defaults.cc#L82

change these too:
```
width_(640),
height_(360),
```
