### ISSUE TITLE
Select Device

### ISSUE THREAD

**Issue by EbramSamy** [radioman/WebRtc.NET#21]
I want to get a list of all available sources for Audio or Video: 
ex : 
- SetAudio --- > Mic or Local Desktop Source
- Video --> All attached cameras 

How to select specific device? 

Thanks :)

**Comment by radioman** [comment]
https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/src/conductor.cc#L263

**Comment by EbramSamy** [comment]
I committed this to get list of available video devices :

std::vector<std::string> Conductor::GetVideoDevices()
{
std::vector<std::string> device_names;
{
std::unique_ptr<webrtc::VideoCaptureModule::DeviceInfo> info(webrtc::VideoCaptureFactory::CreateDeviceInfo(0));
if (info)
{
int num_devices = info->NumberOfDevices();
for (int i = 0; i < num_devices; ++i)
{
const uint32_t kSize = 256;
char name[kSize] = { 0 };
char id[kSize] = { 0 };
if (info->GetDeviceName(i, name, kSize, id, kSize) != -1)
{
device_names.push_back(name);
}
}
}
}
return device_names;
}

------------------------------------


			System::Collections::Generic::List<String ^>^ GetVideoDevices()
			{
				std::vector<std::string>  devicesList = cd->GetVideoDevices();
				array<String ^>^ ret = gcnew array<String ^>(devicesList.size());
				if (devicesList.size())
				{
					for (int i = 0; i < devicesList.size(); i++)
					{
						ret[i] = marshal_as< String ^>(devicesList[i]);
					}
				}
				return gcnew System::Collections::Generic::List<String ^>(ret);
			}

**Comment by sriyanfernando** [comment]
Hi,

Sorry for the interrrupt. id you different video devices then it is working fine.but problem  is can not connect same type  cameras .i want to implement depends on the id?
