### ISSUE TITLE
Audio Devices

### ISSUE THREAD

**Issue by EbramSamy** [radioman/WebRtc.NET#22]
how to set the audio source to the  computer's audio not to the Mic ?
 Or 
how to set the audio source to the default output device ?

**Comment by radioman** [comment]
intall/enable Rec. Playback driver, it's mirror of audio output, therefore you can use it as recording device

**Comment by EbramSamy** [comment]
I tried "hi-fi cable input drive" to simulate the audio output as input but it doesn't work

**Comment by radioman** [comment]
it's 'Rec. Playback', if you don't see it on Recording devices sound settings, you miss drivers, otherwise set it as default, and thats it

dunno if webrtc has selection integrated ;/

**Comment by EbramSamy** [comment]
Thanks :) it worked.
