### ISSUE TITLE
Close Video Capture Device

### ISSUE THREAD

**Issue by EbramSamy** [radioman/WebRtc.NET#23]
How can I close video capture device without closing the application in runtime ?!

**Comment by radioman** [comment]
i guess ManagedConductor.Dispose or ManagedConductor.OpenVideoCaptureDevice(string.Empty)

**Comment by EbramSamy** [comment]
ManagedConductor.Dispose ===> application Crashes 
ManagedConductor.OpenVideoCaptureDevice(string.Empty) ===> Crashes onClosing

**Comment by radioman** [comment]
it 'crashes' on peerconnection destructor, dunno why ;/ but its not related to video capture

**Comment by EbramSamy** [comment]
maybe because of readonly ?!

**Comment by radioman** [comment]
fixed
