### ISSUE TITLE
Debug Libraries in current Release

### ISSUE THREAD

**Issue by Zydraonex** [radioman/WebRtc.NET#27]
I miss the Debug libraries in the current build. It's recommendet when experimenting with webrtc.

**Comment by radioman** [comment]
in the end you will use release build, so why not experiment using it?

**Comment by Zydraonex** [comment]
You can't debug in all circumstances with mixed Release/Debug libs cause it uses different runtime environments. Especially when using other third party libs in the project.

**Comment by radioman** [comment]
yes if you do native dev, it's not my aim though, i guess i could make git submodule for that

**Comment by ashikns** [comment]
Same request here. Could you also provide a little info on how you've built webrtc? Have you modified the source of webrtc for this? do you use any special arguments while building on windows using gn and ninja?

**Comment by radioman** [comment]
the only modification(few missing libs and /MD override) needed is in gn build files: https://github.com/radioman/WebRtc.NET/tree/master/WebRtc.NET/gn

then i use: **gn gen out/ReleaseX86 --ide="vs2015" --args="is_debug=false target_cpu=\"x86\" is_component_build=false symbol_level=0"**

p.s. i'll try to build debug libs

**Comment by radioman** [comment]
fixed, added debug libs and 7zp it, so its even faster checkout
