### ISSUE TITLE
using desktop_capture module

### ISSUE THREAD

**Issue by EbramSamy** [radioman/WebRtc.NET#28]
how can I use the native "desktop_capture" module in the native code ?! 

https://github.com/radioman/WebRtc.NET/tree/master/WebRtc.NET/include/webrtc/modules/desktop_capture

**Comment by radioman** [comment]
dunno about native module, but now you can use c# and custom capturer and push your frames rendering any image g.[CopyFromScreen ](https://msdn.microsoft.com/en-us/library/system.drawing.graphics.copyfromscreen(v=vs.110).aspx) at https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET.Demo/MainForm.cs#L232

**Comment by radioman** [comment]
works quite well: 
![image](https://cloud.githubusercontent.com/assets/709019/22356519/8f19376e-e43a-11e6-96a8-b03e38d51917.png)

**Comment by EbramSamy** [comment]
Yes I know that and I tried it before but what I am doing now to implement it in C++ to get better performance and add a new feature like capturing a specific window that can be implemented in c# but better performance in c++ native code.

**Comment by EbramSamy** [comment]
something like this :  https://groups.google.com/forum/#!topic/discuss-webrtc/R576GLFZf9s

VideoCapturer* DeviceManager::CreateWindowCapturer(talk_base::WindowId window) {
#if defined(WINDOW_CAPTURER_NAME)
  WINDOW_CAPTURER_NAME* window_capturer = new WINDOW_CAPTURER_NAME();
  if (!window_capturer->Init(window)) {
    delete window_capturer;
    return NULL;
  }
  return window_capturer;
#else
  return NULL;
#endif
}

**Comment by radioman** [comment]
does it work?

**Comment by EbramSamy** [comment]
I didn't try it yet but I hope so because it will be better

**Comment by EbramSamy** [comment]
I think it can be tested by creating an object from this capturer:
https://github.com/sukinull/libwebrtc/blob/master/webrtc/modules/desktop_capture/win/screen_capturer_win_gdi.cc

https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/include/webrtc/modules/desktop_capture/win/screen_capturer_win_gdi.h

like capturer_internal :
https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/src/conductor.h#L181

**Comment by EbramSamy** [comment]
#include "webrtc/modules/desktop_capture/win/screen_capturer_win_gdi.h"

webrtc::ScreenCapturerWinGdi

**Comment by EbramSamy** [comment]
the problem now is desktop_capture module isn't built

**Comment by radioman** [comment]
now its included, you can enable it in "internals.h" by setting DESKTOP_CAPTURE 1

**Comment by EbramSamy** [comment]
OK thanks 👍  can I use something like pushframe() to push captured frame? what is the best way to push these captured frames?

**Comment by EbramSamy** [comment]
Can I implement this class for webrtc::DesktopFrame instead of  webrtc::VideoFrame


class VideoRenderer : public rtc::VideoSinkInterface<webrtc::VideoFrame>
	{
	public:
		VideoRenderer(Conductor & c, bool remote, webrtc::VideoTrackInterface * track_to_render) :
			rendered_track_(track_to_render), con(&c), remote(remote)
		{
			rendered_track_->AddOrUpdateSink(this, rtc::VideoSinkWants());
		}
		virtual ~VideoRenderer()
		{
			rendered_track_->RemoveSink(this);
		}

		// VideoSinkInterface implementation
		void OnFrame(const webrtc::VideoFrame& frame) override;

	protected:

		bool remote;
		Conductor * con;
		rtc::scoped_refptr<webrtc::VideoTrackInterface> rendered_track_;		
	};

**Comment by EbramSamy** [comment]
Or Can I use this std::unique_ptr<webrtc::DesktopCapturer> desktop_capturer; instead of cricket::VideoCapturer * vc ; in conductor ?

**Comment by EbramSamy** [comment]
I got it I think that is useful:

https://chromium.googlesource.com/chromium/src/+/731e0e275b0e80df7270ab143597ea4d0d2f1238/remoting/protocol/webrtc_video_capturer_adapter.h#35

https://chromium.googlesource.com/chromium/src/+/731e0e275b0e80df7270ab143597ea4d0d2f1238/remoting/protocol/webrtc_video_capturer_adapter.cc

**Comment by EbramSamy** [comment]
I found also this code and that is useful but the problem is that this build doesn't contain webrtcvideoframefactory and also cricket::VideoCapturer class deosn't have  set_frame_factory(new cricket::WebRtcVideoFrameFactory());  method


https://github.com/Costent/webrtc/blob/master/photon/capturer.cc

https://github.com/Costent/webrtc/blob/master/photon/capturer.h

**Comment by EbramSamy** [comment]
a good option is to send the  frame->data() for webrtc::DesktopFrame to the encoder
That works fine for me :)

**Comment by radioman** [comment]
well thats pretty much the only option ;} .. i just want to add some api for rendering on top of frame, aka CopyFromScreen analog

**Comment by EbramSamy** [comment]
@radioman  another thing is to capture only one window: 

you can use webrtc::DesktopCapturer::CreateWindowCapturer instead of webrtc::DesktopCapturer::CreateScreenCapturer

https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/src/defaults.cc#L68

CreateScreenCapturer worked for me but when I use CreateWindowCapturer it crashes in CaptureFrame or in Decoder 

I don't know why ?

**Comment by EbramSamy** [comment]
you can add this encoder :

int TurboJpegEncoder::EncodeBGRX24toI420(Byte * rgbBuf, Int32 w, Int32 h, Byte * yuv, Int64 yuvSize, Boolean fast)
		{
			int pad = 4;

			int width = w;
			int height = h;
			int pitch = TJPAD(tjPixelSize[TJPF_BGRX] * width);

			if (yuvSize > 0)
			{
				int yuvSizeCheck = tjBufSizeYUV2(width, pad, height, TJSAMP_420);
				if (yuvSizeCheck != yuvSize)
				{
					Debug::WriteLine(String::Format("tjBufSizeYUV2, yuvSizeCheck[{0}] != {1}", yuvSizeCheck, yuvSize));
					return -1;
				}
			}


then send the output of the data of webrtc::DesktopFrame to this encoder and it will work :)

**Comment by radioman** [comment]
i want editing, its not that simple, because capturer use 2 buffer switching queue

**Comment by EbramSamy** [comment]
I already implemented it and it works for me. I am trying to push but Permission to denied.

**Comment by radioman** [comment]
make a fork, i test it

**Comment by EbramSamy** [comment]
Done

**Comment by radioman** [comment]
thanks a lot for a fork, i finally managed to implement editing!

**Comment by EbramSamy** [comment]
You are welcome :) did you try Windowcapturer ?

**Comment by EbramSamy** [comment]
I tested it. It works fine for capturing whole the screen. For capturing a specific window "webrtc::DesktopCapturer::CreateWindowCapturer" It works fine but if you changed your window size while it capturing this window it crashes.

**Comment by radioman** [comment]
there is no size change checks

**Comment by EbramSamy** [comment]
yes so the changing of window size have to be checked in runtime

**Comment by radioman** [comment]
done some testing, checking works, but only if size increase, otherwise: An unhandled exception of type 'System.AccessViolationException' occurred in System.Drawing.dll

**Comment by EbramSamy** [comment]
@radioman I think to pass the buffer pointer to encoder directly will solve the problem like here :
 
https://github.com/EbramSamy/WebRtc.NET/blob/master/WebRtc.NET.Demo/MainForm.cs#L293

**Comment by radioman** [comment]
size is handled correctly at https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET.Demo/MainForm.cs#L267

its some internal capturer bug, at the time of size change, buffer isnt ready yet

**Comment by EbramSamy** [comment]
OK but also there is an issue in performance as if you set the FPS and using window capturer you will get only about 7 Frames

**Comment by radioman** [comment]
https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/src/conductor.cc#L68

**Comment by EbramSamy** [comment]
yes even I set that to 30 for window captruer you will get only about 7 FPS

**Comment by EbramSamy** [comment]
https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET.Demo/MainForm.cs#L278
for this line you draw a rectangle from Curser.point to the screen height and width to capture single app as full-screen mode this line has to be this :
g.DrawImage(captureImg,0,0,screenWidth,screenHeight);

but when I edit this line I get the application as full-screen mode but only 8 FPS even if I set FPS to 35.

![8fps](https://cloud.githubusercontent.com/assets/12788360/24481140/4ebec51a-149d-11e7-9f9b-e0165580e6d9.PNG)

**Comment by radioman** [comment]
you use hd resolution, thats big, dunno if webrtc can handle it

**Comment by EbramSamy** [comment]
Yes webrtc support this resolution and you can check that for desktop capturer you will get 30FPS for 1920*180 resolution but the problem here if capture window with small size then you used `g.DrawImage(captureImg,0,0,screenWidth,screenHeight);` this method will resize the small captured frame that's why you will get low FPS

**Comment by radioman** [comment]
well you can skip resizing if not needed

**Comment by EbramSamy** [comment]
yes I can but the problem will be that I will not get a full-screen application like this
![cap3](https://cloud.githubusercontent.com/assets/12788360/24527397/c61a8a90-1556-11e7-8936-19e716ae10f7.PNG)

**Comment by EbramSamy** [comment]
I will close this issue and I will create another one for windows capturer
