### ISSUE TITLE
 Could not find gn executable at: \src\buildtools\win\gn.exe

### ISSUE THREAD

**Issue by EbramSamy** [radioman/WebRtc.NET#29]
I was trying to build the native code: 
Using this command :
gn gen out/ReleaseX86 --ide="vs2015" --args="is_debug=false target_cpu=\"x86\" is_component_build=false symbol_level=0"

I got this error :
gn.py: Could not find gn executable at: \src\buildtools\win\gn.exe

**Comment by radioman** [comment]
if you want DIY ninja build: https://webrtc.org/native-code/development/

**Comment by EbramSamy** [comment]
The problem was that: 
You have to run this command "set DEPOT_TOOLS_WIN_TOOLCHAIN=0" before run "gclient sync --force"
