### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Globik** [radioman/WebRtc.NET#3]
How to compile all this stuff? Why no documentation? Is it friendly for msbuild 2013??? I have tried to compile but many errors in headers. Why? what does it mean " playdelay no overloaded function takes 2 arguments"? you have a special compiler on your machine?

**Comment by Globik** [comment]
And where is webrtc.net.dll????

**Comment by radioman** [comment]
use vs2015, open solution, WebRtc.NET.App, F5, done.

**Comment by Globik** [comment]
This all stuff compiled successfully to the webrtc.net.app.exe file. But I have now no idea how to use it. When I am clicking on that .exe file nothing is going on. Is this file as a part of c# app? Is a webserver? Or what else could be? When I call webrtc.net.app.exe from the command line there is also nothing to go on. Strange.

**Comment by radioman** [comment]
you should see the same demo as in here, it's simple winForm app hosts demo webrtc stream for the demo web page
![demo](../blob/master/web/demo.gif?raw=true)

**Comment by Globik** [comment]
Yes, now I see. One is a FF browser and one is a server side windows non-console application. It looks like I weirdly compiled webrtc.net.dll. Tested via tools ldd. It shows me two ???? in dependencies track. Looks like linker wrong libs linked. Plus not clear enougth where Debug macro definition and where not.

**Comment by Globik** [comment]
Yes, in the studio IDE from within webrtc.net.app solution I pressed F5. And IDE says me: something wrong with my webrtc.net.dll. Morn I give it a try to recompile .

**Comment by radioman** [comment]
yes, and good luck ;}

**Comment by Globik** [comment]
An issue with lib/jsoncpp.lib  Can't resolve Json::Value simpleVar; simpleVar["putin_suck"]="Russia";
It would be nice if you'll also place your jsoncpp headers here on branch of github. If I take my jsoncpp headers and my jsoncpp.lib plus your jsoncpp.lib , linker complains with an error 2005 plus multiply defines. So if I give to linker the option /force:multiply, the get compiling. That's no good.

**Comment by Globik** [comment]
Yeah, I'm serious. Successfully compiled an example from webrtc chromium. Peer client example. Latest jsoncpp to your stuff does not mutch. One need jsoncpp headers from older times. I took from nacl sdk, pepper_35. Profit.

**Comment by Globik** [comment]
Any way thank you very much for your nice compiled webrtc.net/lib libraries!!!
