### ISSUE TITLE
Using webrtc::DesktopCapturer::CreateWindowCapturer

### ISSUE THREAD

**Issue by EbramSamy** [radioman/WebRtc.NET#30]
Using webrtc::DesktopCapturer::CreateWindowCapturer instead of webrtc::DesktopCapturer::CreateScreenCapturer

https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/src/defaults.cc#L68

CreateScreenCapturer worked for me but when I use CreateWindowCapturer it crashes in CaptureFrame or in decoder 

I don't know why ?

**Comment by radioman** [comment]
dont dublicate

**Comment by EbramSamy** [comment]
This for capturing CreateWindowCapturer not CreateScreenCapturer ... for CreateScreenCapturer it doesn't crash ... it crashes after using CreateWindowCapturer
