### ISSUE TITLE
Byte array

### ISSUE THREAD

**Issue by Terricide** [radioman/WebRtc.NET#32]
Is there a way to send binary data instead of DataChannelSendText there was a DataChannelSendData method?

**Comment by Terricide** [comment]
I added this function. I'm not sure if it is perfect but it is working.

			void DataChannelSendData(array<Byte>^ array_data)
			{
				pin_ptr<Byte> thePtr = &array_data[0];
				BYTE* bPtr = thePtr;
				rtc::CopyOnWriteBuffer writeBuffer;
				writeBuffer.AppendData(bPtr, sizeof(bPtr));
				cd->DataChannelSendData(webrtc::DataBuffer(writeBuffer, true));
			}

**Comment by Terricide** [comment]
There was a small change I had to make and I also made some changes to receive binary data back as well over the data channel. I'll try and get a pull request soon

**Comment by Terricide** [comment]
I just opened a pull request with my changes

**Comment by radioman** [comment]
thanks!
