### ISSUE TITLE
Data Channel

### ISSUE THREAD

**Issue by agallardol** [radioman/WebRtc.NET#34]
Hello,

I am working on a client for PeerJS in .NET using your implementation.

I have had good progress, unfortunately when it comes time to create and open the data channel, this does not work.

Is the data channel implementation working?

Thanks !!

**Comment by radioman** [comment]
it works fine, check demo

**Comment by agallardol** [comment]
Its alive!!! Performing tests we establish the connection by DataChannel and the implementation of PeerJS server and web client. Unfortunately only when both clients (PeerJS Web, PeerJS Server and our .NET application) are on the same computer the connection is established, otherwise the connection can not be established.

At the moment we know that PeerJS server and Web clients are well configured as they manage to establish remote connections over Wifi and 3G.

Thank you very much for everything, we will continue working to discover the problem.

**Comment by radioman** [comment]
excellent!

**Comment by mzielezny** [comment]
@agallardol 
Have you figured what was a problem - I have no problem to connect host by host or over Stun but I'm noticing problems with connecting over Turn - 1 of 20 try connection is working and I have no idea what happen. The same relay over 2 chromes work OK.

**Comment by radioman** [comment]
demo has integrated turn server, works for me

**Comment by mzielezny** [comment]
After a day I have noticed that Turn is working in my case only in release mode - on debug there is no connection and remote side said failed on most of ice gathering. I have some suspectness that it could be caused by logs in libjingle. It is fine that it is working with release but I will also try with newer versions of libraries from WebRTC.org.

**Comment by maxpavlov** [comment]
@mzielezny @agallardol Hi guys. Any plans to make your .NET PeerJS client open source so we can contribute to getting a perfect solution?
