### ISSUE TITLE
Windows 7 issue

### ISSUE THREAD

**Issue by Terricide** [radioman/WebRtc.NET#36]
I'm curious this library is working great on my machines but it is currently causing my app to completely crash on Windows 7. I'm compiling it as a 32-bit library and running my app as a 32-bit process. I don't get anything in the eventlog or on the screen when it crashes.

Do you have any ideas? I'm going to try and install a remote debugger to see if I can figure out the issue.

**Comment by radioman** [comment]
https://github.com/radioman/WebRtc.NET/issues/9

**Comment by radioman** [comment]
p.s. use http://www.dependencywalker.com to check whats missing

**Comment by Terricide** [comment]
[WebRtc.txt](https://github.com/radioman/WebRtc.NET/files/814670/WebRtc.txt)

I've attached the output from dependency walker and I'm not seeing what to look for. I also install Visual Studio 2015 inside the vm and was trying to run the sample directly.

**Comment by radioman** [comment]
hm, try run visual studio then and break on exception?
