### ISSUE TITLE
Implement local audio source to send custom audio

### ISSUE THREAD

**Issue by mysteryjeans** [radioman/WebRtc.NET#39]
Please implement custom audio source equivalent to VideoCapturer, so far google group suggest to implement audio device module.

At least some guide would to good

**Comment by radioman** [comment]
so how its done?

**Comment by mysteryjeans** [comment]
I had just some success by implementing AudioDeviceModule and passed it to create peer factory, basically after all initialization done and StartRecording called and transport callback is not null, than you can pushed 10ms (only) to AudioTransport through RecordedDataIsAvailable. You can use ProcessMessages(10) delay/push data at particular interval. Audio is PCM 16bit mono.

I will share my implementation..

**Comment by radioman** [comment]
thanks!

**Comment by mysteryjeans** [comment]
Here it is: [AudioCaptureModule](https://gist.github.com/mysteryjeans/dfddbf73ab232fd3ef17c51d3b38433d )

**Comment by radioman** [comment]
ok, i'll try to test it, should i hear something and what exactly should i push there?

**Comment by mysteryjeans** [comment]
You need to push PCM 16 bit data only 10ms of data. If you sending 16 bit mono 8KHz recording, then data of 10ms would be 160 bytes and 80 samples in that 10ms frame, in 44Khz recording samples in 10ms frame would 440 and 880 bytes for 1 channel mono 16 bit recording. 
> process delay is key to simulate real-time audio

[WebRTC audio push frame example](https://gist.github.com/mysteryjeans/a9430b1b44c503124be4d094d5ca9fd5)

**Comment by radioman** [comment]
i wonder if i could use fmod to generate some signal, that would be good for demo

**Comment by sagargoyaltrial** [comment]
Hello,
I followed the example.  First thing I do not hear anything, secondly I think we need to register audio callback for this?  also call start recording, and start playout?

**Comment by mysteryjeans** [comment]
No need to call StartRecording, here is implementation of [Conductor](https://gist.github.com/mysteryjeans/0508f5ca87652a830b0c3f281a77ee0e). You need to pushed 10ms frames for audio, for example 8K 16bit Mono will have 160 bytes in 10ms frame.

If you are reading from custom audio file dump, send 10ms frame data and wait in ProcessDelay for rest of the `duration` to passed by.

```csharp
var sampleUnitSize = 16/8 * 1; // Bits/8 * Channels
var rtcFrameSamples = 8000/1000 * 10; // Hz/milliseconds * RTCFrameDuration
var renderedTime = 0L;
var processDelay = 0;
var duration = 100; // 100 milliseconds
var syncTime = Stopwatch.StartNew();
using (var recording = RecordingFactory.CreateRecordingAudio("File.dump....."))
{
    for (var audioStream = recording.GetAudioStream(1, duration).GetEnumerator(); audioStream.MoveNext() && socket.State == WebSocketState.Open && rtcSession.ProcessMessages(processDelay);)
    {
        var buffer = audioStream.Current.GetMergedData();
        unsafe
        {
            fixed (byte* bufferPtr = buffer)
            {
                for (int i = 0; i < buffer.Length; i += (sampleUnitSize * rtcFrameSamples), renderedTime += 10)
                    rtcSession.PushAudioFrame(bufferPtr + i, 16, 8000, 1, 80);
            }
        }
        processDelay = duration - (int)(syncTime.ElapsedMilliseconds - renderedTime);
        if (processDelay < 0) processDelay = 0;
    }
}
```

**Comment by sagargoyal** [comment]
Hello,
Did exactly the same thing, pushing the audio with 10ms of data as well.  But still not able to hear anything.  I have written the audio to a wave file in parallel to sending it to the rtcSession, and the audio is there in the wave file. Any ideas?

**Comment by EbramTawfik** [comment]
@mysteryjeans What is AudioRTPProcessor ?! Is it a NuGet Package?

**Comment by kunaljathal** [comment]
Hi @mysteryjeans , are you still available to answer any questions about your implementation? Can you explain 1) why we are only allowed to send 10ms of audio, and 2) why do we need to "wait" for a duration after pushing a frame?

**Comment by mysteryjeans** [comment]
> Hi @mysteryjeans , are you still available to answer any questions about your implementation? Can you explain 1) why we are only allowed to send 10ms of audio, and 2) why do we need to "wait" for a duration after pushing a frame?
> 
> @sagargoyal were you able to solve your issue?

1) If I remembered correctly RTC accepts only 10ms frame.
2) I was recording from file source on the disk, therefore waiting for duration and also taking processing delays into account as well. If your source is the realtime traffic over TCP, than you will be waiting for next packet but calling ProcessMessages is a must. If your source is realtime but over UDP then you need to implement Jitter buffer as well.

**Comment by kunaljathal** [comment]
I'm still a bit confused about why "calling ProcessMessages is a must". I have an event driven system i.e. whenever there is new audio available, a callback gets triggered which calls `PushFrame` with 10ms of the available audio. So why do I need to call `ProcessMessages` after doing this?

**Comment by mysteryjeans** [comment]
I am not an expert on this. But think of it as Dispatcher in C# world. Dispatcher is was takes control when you called Application.Run() method. In ProcessMessages case it does not run in infinite loop to activate RTC methods.

Did you try calling it after PushFrame for 0 delay?

C or C++ programmer can better explain this.

**Comment by kunaljathal** [comment]
My current situation is the following -- when I try calling just `PushFrame` without calling `ProcessMessages`, I don't hear any audio at the other end. And if I add a `ProcessMessages` call after `PushFrame`, then I get a crash (Access Violation). So at this point I'm trying to understand what the point of `ProcessMessages` is.

I looked at `thread.cpp` in webrtc source where `ProcessMessages` is implemented, and it looks like it just processes messages in it's "queue" (so similar to Dispatcher, like you mentioned). But then the question is, where exactly are we adding messages to the thread queue in the first place? The only thing we are doing is calling `RecordedDataIsAvailable` in `PushFrame`, so it's not clear to me where we are adding audio data to the RTC thread.

I've searched the internet a lot; it looks like you're pretty much the only person who shared their implementation that works, so I appreciate you helping me with this ...

**Comment by mysteryjeans** [comment]
Its probably PushAudioFrame method that queues the message. Please make sure that PushAudioFrame correct parameters.

However my code is old so there are changes that it my not work now, don't lose hope keep trying, thats how I got it to work.

**Comment by kunaljathal** [comment]
`PushAudioFrame` just calls `PushFrame` .... and I can't see how `PushFrame` is queueing messages.

What thread did you call `PushAudioFrame` from ?

**Comment by kunaljathal** [comment]
OK, I figured this out. I'll post a detailed explanation in case this helps anyone out in the future.

I didn't have to call `ProcessMessages` or `PushFrame`. To pass custom audio, you technically just need to create your own source (inherit from `webrtc::LocalAudioSource`) containing a sink, and use its `onData` call to pass custom audio to it. You add your custom audio source to the audio track that you add to your local stream. I did in addition have to write a custom audio device module, but that's only because I also wanted to bypass the mic input. So to recap:

1) You need to create a custom audio device module. You can either write your own one from scratch, or extend the default webrtc implementation. If you extend the default one (which is what I decided to do), you need to make sure that it conforms to webrtc threading requirements for it's own internal audio device. You must pass your custom audio device to the peer connection factory when creating it.

2) Your custom audio device needs to void out all the recording methods and preserve the playback ones if you want to bypass the microphone input.

3) You need to write your own custom audio source which derives from `werbtc::LocalAudioSource` specifically. You add this source to the audio track you add to the local stream. Your custom source should contain a sink. You don't need to implement this sink; only set it in your sources `AddSink` call.

4) When you want to send custom audio data, you simply need to use your `sink->OnData`.

Cheers!

**Comment by edwardsiupactera** [comment]
kunaljathal I am very appreciated that if you can share the working example for me, I try to implement for two week. Now I am able to combine mic and mp3 in webrtc audio device module, but don't know how to add as a audio source for streaming

**Comment by secrecysiu** [comment]
kunaljathal I am very appreciated that if you can share the working example for me, I try to implement for two week. Now I am able to combine mic and mp3 in webrtc audio device module, but don't know how to add as a audio source for streaming

**Comment by kunaljathal** [comment]
Hi @secrecysiu , you can find the code here:
https://groups.google.com/forum/#!searchin/discuss-webrtc/ondata%7Csort:date/discuss-webrtc/f3lIyA3Otyo/mWsQfaYVCAAJ

**Comment by intecoredummy25** [comment]
hi @kunaljathal I have implemented code to pass custom audio over webrtc its working but the sound on other receiving peer has noise , is there any noise parameter i have forgot to add ? Do you have any idea about it ? can you please help, it would be great for me thanks !!!

**Comment by kunaljathal** [comment]
there shouldn't be any parameter for noise. what do you mean by 'noise' anyway? sounds like you are not providing 10ms worth of audio at a rate fast/slow enough ...

**Comment by coreTechie007** [comment]
We are having 16 bit, 44.1 khz stereo channel pcm audio data. We tried to write audio data into file with same way like 10ms of data i.e. 441 samples each time and it gets dump correctly. We could hear clear sound when file played but when we tried same setup it using onData to send over webrtc, we hear some hissing noise on other peer. Have you tried sending stereo data over webrtc ?

**Comment by kunaljathal** [comment]
Hmm, no I don't hear any hissing noise. And yes, I send stereo data over webrtc and it sounds fine.

**Comment by michferrero** [comment]
Hi everyone ... I read the thread but I didn't understand how to use the module "AudioCaptureModule". 
Should it be imported into the WebRTC.NET library? 
How can I import and use it? Esiste un esempio completo su GitHub?

**Comment by michferrero** [comment]
Hi, I have a raw audio track recorded using OpenTK (or other libraries). I should send it to a browser using WebRTC NET. Can you tell me where to find an example of audio-only transmission with WebRTC NET? 
Thanks a lot...
