### ISSUE TITLE
CreateOffer

### ISSUE THREAD

**Issue by Terricide** [radioman/WebRtc.NET#41]
Am I missing how to create the offer from WebRTC.net or does that part of the wrapper need some work?

Right now I have

            session.WebRtc.OnSuccessOffer += WebRtc_OnSuccessOffer;
            session.WebRtc.CreateOffer();

OnSuccessOffer is never called

**Comment by radioman** [comment]
before creating offer call .[InitializePeerConnection](https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/src/managed.cpp#L230)()

also there is _OnFailure/OnError events

**Comment by Terricide** [comment]
Yup it worked when I did this.

            session.WebRtc.AddServerConfig("stun:stun.l.google.com:19302", string.Empty, string.Empty);
            session.WebRtc.AddServerConfig("stun:stun.anyfirewall.com:3478", string.Empty, string.Empty);
            session.WebRtc.AddServerConfig("stun:stun.stunprotocol.org:3478", string.Empty, string.Empty);

            session.WebRtc.OnSuccessOffer += WebRtc_OnSuccessOffer;
            session.WebRtc.OnIceCandidate += WebRtc_OnIceCandidate;
            session.WebRtc.OnSuccessAnswer += WebRtc_OnSuccessAnswer;
            session.WebRtc.OnFailure += WebRtc_OnFailure;
            session.WebRtc.OnError += WebRtc_OnError;
            session.WebRtc.OnDataBinaryMessage += WebRtc_OnDataBinaryMessage;
            session.WebRtc.OnDataMessage += WebRtc_OnDataMessage;

            webRtcTask = Task.Run(() =>
            {
                var ok = session.WebRtc.InitializePeerConnection();
                if (ok)
                {
                    session.WebRtc.CreateOffer();
                    // javascript side makes the offer in this demo
                    //session.WebRtc.CreateDataChannel("msgDataChannel");

                    while (!session.Cancel.Token.IsCancellationRequested &&
                           session.WebRtc.ProcessMessages(3))
                    {
                        //Debug.Write(".");
                    }
                    session.WebRtc.ProcessMessages(3);
                    IsReady = false;
                }
                else
                {
                    Debug.WriteLine("InitializePeerConnection failed");
                    IsReady = false;
                }
            });
