### ISSUE TITLE
Cant run project, lib.7z extraction

### ISSUE THREAD

**Issue by Decay1991** [radioman/WebRtc.NET#42]
Hi, I am trying to run the example in Visual Studio 2017 and it is not working. When I it Run and the project compiles it says that the WebRtc.NET.dll is not found, but before compiling it was there. Can someone please tell me how to Run this example. 

Thanks

**Comment by radioman** [comment]
its not vs2017 compatible yet

**Comment by Decay1991** [comment]
but the same thing hapends on Visual Studio 2015. I open the solution on the example, change from debug to release and run. What am I doing wrong? do I need to do something before?

**Comment by radioman** [comment]
did you extracted libs?

**Comment by Decay1991** [comment]
no. Where do I put de extracted libs?

**Comment by radioman** [comment]
at the same directory, each zip is just compressed folder

**Comment by Alexlander** [comment]
I extracted the libs, still I get WebRtc.NET.dll is not found when I try to run, am I missing something?
