### ISSUE TITLE
Cannot run any build on Windows 7

### ISSUE THREAD

**Issue by Codeusa** [radioman/WebRtc.NET#43]
I've tried just about everything and the project fails to run on Windows 7

I've made sure to include DLLs and I've tried both debug and release builds. Nothing works. The native DLL is missing dependencies and when the C# application calls it, it crashes. 

```
Faulting application name: WebRtc.NET.Demo.exe, version: 1.0.0.0, time stamp: 0x58caf309
Faulting module name: KERNELBASE.dll, version: 6.3.9600.16384, time stamp: 0x52158f2d
Exception code: 0xe0434352
Fault offset: 0x00013d67
Faulting process id: 0xca0
Faulting application start time: 0x01d29e929162ffd1
Faulting application path: C:\Users\Andrew\Documents\WebRtc.NET.Demo.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: d72c34fc-0a85-11e7-8250-000c290577f8
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: WebRtc.NET.Demo.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at WebRtc.NET.Demo.MainForm..ctor()
   at WebRtc.NET.Demo.MainForm.Main()
```

If you have some clearer steps that need to be taken to build for Windows 7, I'd appreciate it, as it stands only 10 and 8 seem to work.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=43121964)](https://www.bountysource.com/issues/43121964-cannot-run-x64-build-on-windows-7?utm_source=43121964&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Codeusa** [comment]
As a quick update, I was able to get it to run on Windows 8 by including the entire ucrt folder with the release build. However Windows 7 still does not work.

**Comment by Codeusa** [comment]
These issued can be resolved by ensuring Windows is completely up-to-date.

**Comment by EbramSamy** [comment]
Is it working for windows 7 X86 ?

**Comment by Codeusa** [comment]
I stand corrected, I'm unable to get it to run on Windows 7 even with all Windows updates present.

**Comment by Codeusa** [comment]
I've tested with both x86 and x64, both build fine however neither runs on Windows 7.

- The correct visual studio redistributables are installed (in my case 2017).
- KB2999226 is installed on the Windows 7 machine, this should allow for Universal CRT. 

I've attached the results from Dependency Walker 
[WebRtc.txt](https://github.com/radioman/WebRtc.NET/files/849519/WebRtc.txt)

Hopefully this points you in the right direction to finding what causes the failure.

**Comment by Terricide** [comment]
I'm betting that if all the webrtc chrome libraries were compiled on windows 7 I bet it would start working.

**Comment by radioman** [comment]
webrtc.net target is set for [_WIN32_WINNT_WIN7  ](https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/targetver.h#L9)
and libs are built using [_WIN32_WINNT=0x0601](https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/gn/build/config/win/BUILD.gn#L208)

..so it should be compatible, but dunno its a ninja stuff! ;/ ..and i'm building on win10, target 8.1

..keep in mind by default its set to [<PlatformToolset>v140</PlatformToolset>](https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/WebRtc.NET.vcxproj#L32) but you could try toolset v140_xp:

![image](https://cloud.githubusercontent.com/assets/709019/24066310/f13ebffc-0b79-11e7-8b56-dad965bd6d87.png)

**Comment by Terricide** [comment]
I tried that when I when I was trying to figure it out and it didn't help. It literally crashes before I can hit any breakpoint.

**Comment by radioman** [comment]
well i dont have vs2010 for testing, and vs2017 is 40GB, even more 'fun'...

**Comment by Terricide** [comment]
vs2015 can run on Windows 7 I will try next week to do all the ninja stuff on windows 7 and report back

**Comment by Codeusa** [comment]
I've built it with vs2010 and 2017 XP mode and neither work.

@radioman 

Managed Debugging Assistant 'FatalExecutionEngineError'  occurred
  HResult=0x00000000
  Message=**Managed Debugging Assistant 'FatalExecutionEngineError' :** 'The runtime has encountered a fatal error. The address of the error was at 0xeeaa3167, on thread 0x10ac. The error code is 0x80131506. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'

**Comment by radioman** [comment]
..i've found my old virtual xp box and figured few missing dll(according [ms blog](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/) you need to deploy **C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86\\*.dll**), and there are few functions that kernel32.dll does not implement, though on win7 it should work:

- WakeAllConditionVariable
- SleepConditionVariableCS
- WakeConditionVariable
- InitializeConditionVariable
- InitializeCriticalSectionEx
- InitOnceExecuteOnce
- AcquireSRWLockShared
- AcquireSRWLockExclusive
- ReleaseSRWLockShared
- ReleaseSRWLockExclusive
- InitializeSRWLock

**Comment by Codeusa** [comment]
@radioman I've included all the DLL's in that folder as mentioned before, however it still does not load on Windows 7.

**Comment by Codeusa** [comment]
For some more context I just tested more on Windows 7 and the x64 build throws a BadImageFormat exception, the x86 build exits with code 80131506

**Comment by EbramSamy** [comment]
By enabling native debugging for demo Project :
![capture2](https://cloud.githubusercontent.com/assets/12788360/24124170/a6870f84-0d7f-11e7-9318-af404777abed.PNG)



I got this exception for NTDLL.dll :


Exception thrown at 0x000007FEFC4DA06D in WebRtc.NET.Demo.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000000005CAEA8.
Exception thrown at 0x00000000779CC55B (ntdll.dll) in WebRtc.NET.Demo.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

**Comment by EbramSamy** [comment]
An when I was checking it using dependency walker I found that : 
![capture 3](https://cloud.githubusercontent.com/assets/12788360/24124565/8daa71ac-0d81-11e7-8ac8-f05dc21e04b7.PNG)

**Comment by Codeusa** [comment]
@radioman I've opened a bounty source for this issue as I feel it will help this project grow. The reward is $100.

https://www.bountysource.com/issues/43121964-unable-to-run-on-windows-7

**Comment by daveime** [comment]
@Codeusa Just gone though the same steps, seeing similar x86 and x64 error messages on my machine - Windows 7 SP1, VS 2015 Enterprise Update 3. Upon loading the project, had to upgrade the following items first. 

Common Tools for Visual C++ 2015
Windows 8.1 SDK and Universal CRT SDK

Did that, unzipped the libraries, copied all the UCRT dlls into the debug / release output folders, and I get this.

Debug x86
An unhandled exception of type 'System.BadImageFormatException' occurred in WebRtc.NET.Demo.exe
Additional information: Could not load file or assembly 'WebRtc.NET.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)

Debug x64
An unhandled exception of type 'System.AccessViolationException' occurred in WebRtc.NET.Demo.exe
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

I'd just add that when building the various outputs, I'm seeing around 15-20 warnings about type conversions - floats to ints, sizes to uints,etc. in both 32 and 64 bit flavors, but nothing to indicate pointers or memory addresses might be getting munged. Also an "invalid subsystem version number 5.01" on the 64 bit builds.

Will be monitoring this thread and trying to work things out myself, as I'm very interested in getting a working WebRTC library under C#.

**Comment by Terricide** [comment]
Right now I am using this library "http://www.meshcommander.com/webrtc" for Windows 7 support. However I cannot get that library working across the internet only between two systems on the same network.

**Comment by daveime** [comment]
@Terricide Yes, I had looked at that, but seems it's data only - and my specific use-case is data + audio streams.

@Codeusa I've tried DependencyWalker myself, and not the following issues for my the x64 Debug build.

1 - IESHIMS.DLL is "missing", and the parent IEFRAMES.DLL depends on that. IEFRAMES.DLL is reporting 3 missing functions #141, #159,#160. 
2 - SHLWAPI.DLL is reporting missing functions #270, SHELL32.DLL depends on that, and IEFRAMES.DLL depends on that.

So I'm going to try and source / research this IESHIMS.DLL and why what are seemingly Internet Explorer (ewww) DLLs are part of a Chromium source. 

Will post back any news.

**Comment by daveime** [comment]
@Codeusa Just an update after consulting Geoff Chappells excellent resource http://www.geoffchappell.com, and finding the IEShims.dll in the Internet Explorer 8 install. After pasting the x86 and x64 DLLs into the output directory, that at least is one less error in DependencyWalker!

The reported missing functions are :-

shlwapi.dll #270 GUIDFromStringW (5.0 and higher)

ieframe.dll #141 IEInvalidateImageList (7.0 and higher)
ieframe.dll #159 SHRestricted2W (7.0 and higher)
ieframe.dll #160 SHIsRestricted2W (7.0 and higher)

Now I seem to have suitable versions of DLLs on my system

Internet Browser (Vista, Windows 7, Windows Server 2008)
C:/Windows/System32/ieframe.dll
C:/Windows/SysWOW64/ieframe.dll
version 8.0.7601.17514

Shell Lightweight Utility (Windows 7)
C:/Windows/System32/shlwapi.dll
C:/Windows/SysWOW64/shlwapi.dll
version 6.1.7601.17514

Which corresponds to the versions Geoffs website suggests I should have for my O/S and Internet Explorer version etc.

So I'm at a loss now whether those DLLs are the problem, or it's just this "late load" thing that DependencyWalker can't handle/detect.

**Comment by Terricide** [comment]
I spoke to my boss about adding to the bounty. Can the bounty address 32-bit as well as 64-bit?

**Comment by Codeusa** [comment]
I've edited the title @Terricide so it applies to both x86 and x64.

**Comment by radioman** [comment]
..my install vs2017 is ok, i'll try rebuild all libs targeting for xp

**Comment by Terricide** [comment]
I just added $100 to the bounty :)

**Comment by Codeusa** [comment]
Thanks @Terricide 

As a heads up @radioman as the maintainer, you're still eligible to collect the bounty if you fix it.

**Comment by radioman** [comment]
good news, XPsp3 build & run, no missing functions
![image](https://cloud.githubusercontent.com/assets/709019/24186687/0e3c2cdc-0ee2-11e7-84ea-62bebf1564a8.png)

**Comment by Codeusa** [comment]
That is indeed great news @radioman, once all the changes are pushed I'll verify Windows 7 is working and you can claim the bountysource.

**Comment by Terricide** [comment]
That is awesome I would love to be able to support down to Windows XP :)

**Comment by Codeusa** [comment]
Hey @radioman is there an ETA when you might push the newly compiled libraries?

**Comment by radioman** [comment]
dunno, there is issue on xp in managed lib

**Comment by Codeusa** [comment]
Can you provide any additional details @radioman so we might be able too help?

**Comment by radioman** [comment]
i'll make a staging branch for testing on win7/xp..

**Comment by radioman** [comment]
https://github.com/radioman/WebRtc.NET/tree/staging

only  Release x86, even no missing functions on xp, i still get:

```
--------------------------------------------------------------------------------
Starting profile on 2017-03-30 at 22:11:43

Operating System: Microsoft Windows XP Professional (32-bit), version 5.01.2600 Service Pack 3
Program Executable: c:\documents and settings\administrator\desktop\release\WEBRTC.NET.DEMO.EXE
Program Arguments: 
Starting Directory: C:\Documents and Settings\Administrator\Desktop\Release\
Search Path: C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0

Options Selected:
     Simulate ShellExecute by inserting any App Paths directories into the PATH environment variable.
     Log DllMain calls for process attach and process detach messages.
     Log DllMain calls for all other messages, including thread attach and thread detach.
     Hook the process to gather more detailed dependency information.
     Log LoadLibrary function calls.
     Log GetProcAddress function calls.
     Log first chance exceptions.
     Log debug output messages.
     Use full paths when logging file names.
     Automatically open and profile child processes.
--------------------------------------------------------------------------------

Started "c:\documents and settings\administrator\desktop\release\WEBRTC.NET.DEMO.EXE" (process 0x128) at address 0x00400000.  Successfully hooked module.
Loaded "c:\windows\system32\NTDLL.DLL" at address 0x7C900000.  Successfully hooked module.
Loaded "c:\windows\system32\MSCOREE.DLL" at address 0x79000000.  Successfully hooked module.
Loaded "c:\windows\system32\KERNEL32.DLL" at address 0x7C800000.  Successfully hooked module.
DllMain(0x7C900000, DLL_PROCESS_ATTACH, 0x00000000) in "c:\windows\system32\NTDLL.DLL" called.
DllMain(0x7C900000, DLL_PROCESS_ATTACH, 0x00000000) in "c:\windows\system32\NTDLL.DLL" returned 1 (0x1).
DllMain(0x7C800000, DLL_PROCESS_ATTACH, 0x00000000) in "c:\windows\system32\KERNEL32.DLL" called.
DllMain(0x7C800000, DLL_PROCESS_ATTACH, 0x00000000) in "c:\windows\system32\KERNEL32.DLL" returned 1 (0x1).
Injected "z:\e\software\depends22_x86\DEPENDS.DLL" at address 0x08370000.
DllMain(0x79000000, DLL_PROCESS_ATTACH, 0x00000000) in "c:\windows\system32\MSCOREE.DLL" called.
DllMain(0x08370000, DLL_PROCESS_ATTACH, 0x00000000) in "z:\e\software\depends22_x86\DEPENDS.DLL" called.
DllMain(0x08370000, DLL_PROCESS_ATTACH, 0x00000000) in "z:\e\software\depends22_x86\DEPENDS.DLL" returned 1 (0x1).
GetProcAddress(0x7C800000 [c:\windows\system32\KERNEL32.DLL], "FlsAlloc") called from "c:\windows\system32\MSCOREE.DLL" at address 0x79006F3C and returned 0xFFBADD11.
Exited "c:\documents and settings\administrator\desktop\release\WEBRTC.NET.DEMO.EXE" (process 0x128) with code -1073740791 (0xC0000409).
```

**Comment by Codeusa** [comment]
@radioman would it be possible to get a build that allows the toggling of features from the compile? Or just to see if it works, a build with data channel only.

It seems like this is a dependency issue, I'm just curious if a version that doesn't attempt to do anything video/audio related will run.

**Comment by radioman** [comment]
thats not the issue

**Comment by Codeusa** [comment]
What do you think it could be? From research it seems like the project will indeed need to be built with VS 2013 for compatibility with Windows 7.

**Comment by radioman** [comment]
webrtc does not build using vs2010, dunno about vs2013

**Comment by EbramSamy** [comment]
@radioman @Codeusa  is there any update?

**Comment by radioman** [comment]
does staging branch work on win7?

**Comment by Codeusa** [comment]
@radioman unfortunately no

**Comment by radioman** [comment]
same error? Then i guess its compiler issue ;/

**Comment by Codeusa** [comment]
Yeah it is the same issue, I recommend trying to build it using 2013 and seeing if that works.

**Comment by radioman** [comment]
i've managed to test it on win7sp1, there is no missing functions on win7 and no missing dlls, but its fail anyway **STATUS_STACK_BUFFER_OVERRUN**, random $ms failure or its deliberate to drop support quietly, what a morons.. anyway i try updates! ;}
```
00:00:00.234: GetProcAddress(0x77350000 [c:\windows\system32\KERNEL32.DLL], "FlsAlloc") called from "c:\windows\system32\MSCOREE.DLL" at address 0x6DCE6F3C and returned 0x773A418D by thread 1.
00:00:00.234: 
00:00:00.234: STATUS_STACK_BUFFER_OVERRUN encountered
00:00:00.250: Entrypoint reached. All implicit modules have been loaded.
00:00:00.250: Exited "c:\users\administrator\desktop\release\WEBRTC.NET.DEMO.EXE" (process 0x49C) with code -1073740791 (0xC0000409) by thread 1.
```

**Comment by radioman** [comment]
![image](https://cloud.githubusercontent.com/assets/709019/24774804/fc0969f6-1b22-11e7-96af-7bfb1de285c3.png)

yep... ;/

**Comment by Codeusa** [comment]
While inconvenient, you can make a Windows 7 ISO with all updates.

https://www.howtogeek.com/255540/the-last-windows-7-iso-youll-ever-need-how-to-slipstream-the-convenience-rollup/

**Comment by EbramSamy** [comment]
@radioman I want to get  Release x64 to test it.

**Comment by Codeusa** [comment]
Yeah I should add @radioman I should add x64 is the target goal

**Comment by radioman** [comment]
the goal is to find the 'cure' ;}

**Comment by radioman** [comment]
win7, native console, same webrtc libs, behold, no problems, so it means its c++/cli issue! ;/

```
int main()
{
auto pc_factory_ = webrtc::CreatePeerConnectionFactory();
}
```

**Comment by radioman** [comment]
after moving test function to managed.cpp with /clr support i get the same old error, that means there is some dumb $ms internal error on clr initialization.

```
00:00:00.405: GetProcAddress(0x76480000 [c:\windows\system32\KERNEL32.DLL], "FlsAlloc") called from "c:\windows\system32\MSCOREE.DLL" at address 0x6EFF6F3C and returned 0x764D418D by thread 1.
00:00:00.436: 
00:00:00.436: STATUS_STACK_BUFFER_OVERRUN encountered
```

**Comment by radioman** [comment]
anyone know how to use the old way? https://msdn.microsoft.com/en-us/library/ms173266.aspx

**Comment by Codeusa** [comment]
If I recall, FlsAlloc is only supported by .NET 4.5, but you target 4.0.

I would guess that the Win 7 problem is somehow connected with static code in the DLL (static initialization happening to early and confusing the initialization and DLL load in general).

**Comment by radioman** [comment]
P/Invoke it is!

**Comment by radioman** [comment]
![image](https://cloud.githubusercontent.com/assets/709019/24883032/e22d2622-1e4b-11e7-9daa-f52ac52381d4.png)

**Comment by Codeusa** [comment]
Awesome @radioman, when can we expect a push?

**Comment by Terricide** [comment]
That is so awesome!!!

**Comment by Terricide** [comment]
It looks like it is is already in the staging branch or at least a good start of it

**Comment by EbramSamy** [comment]
I tested it it works fine but if I enable DESKTOP_CAPTURE I get "Can't open file desktp_capture.lib"

works fine :
![capture_2](https://cloud.githubusercontent.com/assets/12788360/24920271/755960a6-1e9b-11e7-8cbe-92ddeafc70c3.png)


if I enable DESKTOP_CAPTURE 
![capture_1](https://cloud.githubusercontent.com/assets/12788360/24920292/85ad03f4-1e9b-11e7-992b-affd5920a920.PNG)

**Comment by radioman** [comment]
yes, capture isnt ready yet

**Comment by EbramSamy** [comment]
Thanks, @radioman :) 
another thing this method should be public: 
https://github.com/radioman/WebRtc.NET/blob/staging/WebRtc.NET/WebRtcNative.cs#L71

**Comment by Terricide** [comment]
I just tried the staging branch cpu set to x86 on 64-bit windows 7 os using my software and it works :)

**Comment by EbramSamy** [comment]
I tested it for Win 7 x64 and Win 8 x86 VM and it works fine.

**Comment by EbramSamy** [comment]
to GetVideoDevices you can use this code : 
       

for conductor.h :

#include "atlsafe.h"

static LPSAFEARRAY GetVideoDevices();


for conductor.cc :

__declspec(dllexport) LPSAFEARRAY GetVideoDevices()
	{
		return Native::Conductor::GetVideoDevices();
	}
	
	
	
	LPSAFEARRAY Conductor::GetVideoDevices()
	{
		std::vector<std::string> device_names;
		{
			std::unique_ptr<webrtc::VideoCaptureModule::DeviceInfo> info(webrtc::VideoCaptureFactory::CreateDeviceInfo());
			if (info)
			{
				int num_devices = info->NumberOfDevices();
				for (int i = 0; i < num_devices; ++i)
				{
					const uint32_t kSize = 256;
					char name[kSize] = { 0 };
					char id[kSize] = { 0 };
					if (info->GetDeviceName(i, name, kSize, id, kSize) != -1)
					{
						device_names.push_back(name);
					}
				}

			}
			
		}
		
		CComSafeArray<BSTR> a(device_names.size()); // cool ATL helper that requires atlsafe.h

		std::vector<std::string>::const_iterator it;
		int i = 0;
		for (it = device_names.begin(); it != device_names.end(); ++it, ++i)
		{
			// note: you could also use std::wstring instead and avoid A2W conversion
			a.SetAt(i, A2BSTR_EX((*it).c_str()), FALSE);
		}
		return a.Detach();
	}
	
	
for WebRtcNative.cs : 

[DllImport(dll)]
        [return: MarshalAs(UnmanagedType.SafeArray)]
        static extern string[] GetVideoDevices();
        public static string[] VideoDevices()
        {
            return GetVideoDevices();
        }

**Comment by Terricide** [comment]
FYI now that it has been broken up from WebRTCNative you can actually very easily compile the WebRTC.Net.dll down to as low as .net 2.0

**Comment by Codeusa** [comment]
Once there is a stable master @radioman feel free to claim the bounty.

**Comment by radioman** [comment]
done, whats next? win98 support ;}

**Comment by Codeusa** [comment]
@radioman am i missing something or is stdafx now missing from staging? I can't build from source anymore.

**Comment by radioman** [comment]
its gone

**Comment by Codeusa** [comment]
There are errors on build stating it is missing and additional errors when precompiled headers are disabled about being unable to find webrtc-all.lib just so you're aware

**Comment by radioman** [comment]
works fine for me

**Comment by Terricide** [comment]
I was able to build a 32-bit WebRTCNative.dll because all the correct files were in the lib.zip file however the 64-bit lib_64.zip doesn't contain the correct files.

**Comment by radioman** [comment]
there is no x64 version yet

**Comment by Terricide** [comment]
Codeusa, I'm just curious do you need it to be 64-bit? The 32-bit version works great on 64-bit windows.

**Comment by Codeusa** [comment]
Yeah I need a 64
-bit build as my application is 64-bit only, so a 32-bit dll cannot be
loaded.

**Comment by Codeusa** [comment]
Hey @radioman just wanted to check to see if you had any ETA when the new version would be complete.

**Comment by radioman** [comment]
i guess today is the day

**Comment by Terricide** [comment]
Hi @radioman what do you think about doing this? So that the WebRTC.Net assembly could be set to anycpu then load the native dll dynamically? I grabbed this source from how SQLite dot net works.

public class WebRtcNative : IDisposable
    {
        static WebRtcNative()
        {
            int ptrSize = IntPtr.Size;
            var architectureDirectory = (ptrSize == 8 ? "x64" : "x86");
            var interopFilename = "WebRtcNative.dll";

            string interopPath = null;

            if (interopPath == null)
            {
                // no NativeInteropSearchPath given (or nothing found using this path) so load native library from assembly execution direcotry
                string assemblyCurrentPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
                string relativePath = architectureDirectory + "\\" + interopFilename;
                string assemblyInteropPath = Path.Combine(Path.Combine(assemblyCurrentPath, architectureDirectory), interopFilename);

                // try relative to assembly first, if that does not exist try relative to working dir
                interopPath = File.Exists(assemblyInteropPath) ? assemblyInteropPath : relativePath;
            }

            IntPtr ret = LoadLibrary(interopPath);
            if (ret == IntPtr.Zero)
            {
                throw new Exception("Failed to load native sqlite library from " + interopPath);
            }
        }

        [DllImport("kernel32", SetLastError = true, CharSet = CharSet.Unicode)]
        private static extern IntPtr LoadLibrary(string lpFileName);
        const string dll = "WebRtcNative";

**Comment by radioman** [comment]
thanks for the hint!

**Comment by Codeusa** [comment]
```csharp
 private const string X64DllName = "WebRtcNative-x64.dll";
        private const string X86DllName = "WebRtcNative-x86.dll";

        public static void SetupDll()
        {
            var myPath = new Uri(typeof(WebRtcUtils).Assembly.CodeBase).LocalPath;
            var myFolder = Path.GetDirectoryName(myPath);
            if (string.IsNullOrWhiteSpace(myFolder))
            {
                throw new InvalidOperationException("WebRTC Missing.");
            }
            var is64 = IntPtr.Size == 8;
            var dllPath = Path.Combine(myFolder, is64 ? X64DllName : X86DllName);
            var newPath = Path.Combine(myFolder, "WebRtcNative.dll");
            if (File.Exists(dllPath))
            {
                System.IO.File.Copy(dllPath, newPath, true);
                Console.WriteLine($"Set {dllPath} to {newPath}");
            }
        }
```

**Comment by Terricide** [comment]
It is looking pretty good. Another quick potential enhancement would be to gzip the WebRtcNative dll's to shrink the binary file down like this.

                using (var ms = new MemoryStream(Resources.WebRtcNative_x86_dll))
                using (var fs = new FileStream(file, FileMode.Create))
                using (var gz = new GZipStream(ms, CompressionMode.Decompress))
                {
                    byte[] buffer = new byte[32768];
                    int read;
                    while ((read = gz.Read(buffer, 0, buffer.Length)) > 0)
                    {
                        fs.Write(buffer, 0, read);
                    }
                }

**Comment by radioman** [comment]
yep, the downside is its needs manual 'zipping' after each build

**Comment by Codeusa** [comment]
@radioman any chance you can write up some docs on building the WebRTC code?
