### ISSUE TITLE
WebRTC.NET to WebRTC.NET

### ISSUE THREAD

**Issue by Terricide** [radioman/WebRtc.NET#44]
Hi I'm struggling to get webrtc working on both ends. Do you have any guidance? Or should I show you the code so far. I'm creating the offer and passing it over with ice candidates but only one side seems to generate the ice candidates.

**Comment by radioman** [comment]
on the other side use: [OnOfferRequest](https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/src/managed.cpp#L270), on success event send sdp back and apply OnOfferReply, inverse of javascript demo

**Comment by Terricide** [comment]
When do I create the datachannel? At the very beginning or after OnOfferReply?

**Comment by radioman** [comment]
in js demo its after peeer init before createOffer:  https://github.com/radioman/WebRtc.NET/blob/master/web/rtc_main.js#L80

**Comment by Terricide** [comment]
Sorry I keep asking questions but onofferreply has

public void OnOfferReply(string type, string sdp);

Do you know what the type parameter should be?

**Comment by radioman** [comment]
"offer" / "answer"

**Comment by Terricide** [comment]
I pass in "answer" and the sdp and the function never returns.

**Comment by Terricide** [comment]
nevermind I got it working. thanks for the help :)

**Comment by radioman** [comment]
p.s. if you can, share your findings, i could integrate it into demo

**Comment by SammyBravo** [comment]
I seem to be stuck in the same place @Terricide was until they got it working.  OnOfferReply(string type, string sdp) doesn't seem to be working. I've used "answer" as the type but no luck. Help please??
