### ISSUE TITLE
'WebRtc.NET.dll' could not be found

### ISSUE THREAD

**Issue by vasu494** [radioman/WebRtc.NET#47]
when i built the solution I am getting this error

1.Error	CS0006	Metadata file 'F:\gitfolder\webrtc\WebRtc.NET\Debug_x64\WebRtc.NET.dll' could not be found	
2.Error	The type or namespace name 'TurboJpegEncoder' could not be found (are you missing a using directive or an assembly reference?)
3.Error	The name 'TJPF' does not exist in the current context	
4.Error	The name 'ManagedConductor' does not exist in the current context
5.Error	Failed to locate: "CL.exe". The system cannot find the file specified.

**Comment by vasu494** [comment]
Error	The type or namespace name 'TurboJpegEncoder' could not be found (are you missing a using directive or an assembly reference?)

**Comment by radioman** [comment]
https://github.com/radioman/WebRtc.NET/issues/42

**Comment by vasu494** [comment]
yes, now its working as expected in vs2017
