### ISSUE TITLE
How to run on Visual Studio 2013

### ISSUE THREAD

**Issue by Alexlander** [radioman/WebRtc.NET#48]
I extracted the libs, still I get WebRtc.NET.dll is not found.
So I get ` Error	2	error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...".	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets	64	5	WebRtc.NET`

Went back to v120 but get a lot of C++ does not support default int. How can make this work like on Visual Studio 2015 :rofl:

**Comment by Alexlander** [comment]
http://landinghub.visualstudio.com/visual-cpp-build-tools installing this will work I guess :)

**Comment by radioman** [comment]
if you use c#, you can use prebuilt dll, otherwise vs2015 toolset, works in vs2017 also
