### ISSUE TITLE
WebRtc.NET.dll is not a valid Win32 application

### ISSUE THREAD

**Issue by Globik** [radioman/WebRtc.NET#5]
At runtime of webrtc.net.app.exe pops up a window saying webrtc.net.dll is not a valid win32 application.
What does it mean? I checked with an ldd-utils a dependencies track of this dll. You have on your platform also like that?
A command ldd.exe webrtc.net.dll that gives this output:
 ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x77040000)
        kernel32.dll => /c/Windows/system32/kernel32.dll (0x76420000)
        KERNELBASE.dll => /c/Windows/system32/KERNELBASE.dll (0x752c0000)
        ??? => ??? (0x55b40000)
        ??? => ??? (0x6ee10000)
Broken I see. With interesse let's compare that litjson.dll for example:
ldd.exe litjson.dll:
 ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x77040000)
        kernel32.dll => /c/Windows/system32/kernel32.dll (0x76420000)
        KERNELBASE.dll => /c/Windows/system32/KERNELBASE.dll (0x752c0000)
        MSCOREE.DLL => /c/Windows/SYSTEM32/MSCOREE.DLL (0x6ee10000)
        ADVAPI32.dll => /c/Windows/system32/ADVAPI32.dll (0x767c0000)
        msvcrt.dll => /c/Windows/system32/msvcrt.dll (0x75fa0000)
        sechost.dll => /c/Windows/SYSTEM32/sechost.dll (0x76100000)
        RPCRT4.dll => /c/Windows/system32/RPCRT4.dll (0x76cd0000)
        SHLWAPI.dll => /c/Windows/system32/SHLWAPI.dll (0x77230000)
        GDI32.dll => /c/Windows/system32/GDI32.dll (0x768f0000)
        USER32.dll => /c/Windows/system32/USER32.dll (0x76500000)
        LPK.dll => /c/Windows/system32/LPK.dll (0x75f90000)
        USP10.dll => /c/Windows/system32/USP10.dll (0x76060000)
        IMM32.DLL => /c/Windows/system32/IMM32.DLL (0x76870000)
        MSCTF.dll => /c/Windows/system32/MSCTF.dll (0x76120000)
        mscoreei.dll => /c/Windows/Microsoft.NET/Framework/v4.0.30319/mscoreei.dll (0x6a250000)
We see all is in place. Why webrtc.net.dll sucks I don't understand.
Let's look at webrtc.net.applib.dll:
ldd.exe webrtc.net.applib.dll:
 ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x77040000)
        kernel32.dll => /c/Windows/system32/kernel32.dll (0x76420000)
        KERNELBASE.dll => /c/Windows/system32/KERNELBASE.dll (0x752c0000)
        MSCOREE.DLL => /c/Windows/SYSTEM32/MSCOREE.DLL (0x6ee10000)
        ADVAPI32.dll => /c/Windows/system32/ADVAPI32.dll (0x767c0000)
        msvcrt.dll => /c/Windows/system32/msvcrt.dll (0x75fa0000)
        sechost.dll => /c/Windows/SYSTEM32/sechost.dll (0x76100000)
        RPCRT4.dll => /c/Windows/system32/RPCRT4.dll (0x76cd0000)
        mscoreei.dll => /c/Windows/Microsoft.NET/Framework/v4.0.30319/mscoreei.dll (0x6a250000)
Also in place all. But what's wrong with webrtc.net.dll?

**Comment by Globik** [comment]
Короче гавно ебаное твой код на си шарп.

**Comment by radioman** [comment]
it's valid idiot ;/

**Comment by radioman** [comment]
probably missing VCRUNTIME140.DLL

=> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT
