### ISSUE TITLE
EncodeI420() doesn't exist (with WebRTC.Net.dll)

### ISSUE THREAD

**Issue by Alexlander** [radioman/WebRtc.NET#50]
Trying to use TurboJpegEncoder but the method EncodeI420 doesn't exist, only JPEG to I420 and stuff.

Can only use the DLL sadly, so if anyone can check why EncodeI420 doesnt exist and update the DLL is nececarry thank you!

**Comment by radioman** [comment]
check prerelease version at https://github.com/radioman/WebRtc.NET/blob/staging/WebRtc.NET/WebRtcNative.cs#L174

you dont need to deal with i420 anymore, its integrated

**Comment by Alexlander** [comment]
Nice, another question, should I just use the C# copyscreen function or the "WebRTC native" one? Any differences between the two? I just want to capture my entire screen or a part of it

**Comment by radioman** [comment]
integrated capturer use directx, its should perform better, the result is the same

**Comment by Alexlander** [comment]
Can't see the WebRTC.NET.dll, only the webRTCnative one when I download the prerelease version

**Comment by radioman** [comment]
its not, WebRTC.NET is

**Comment by Alexlander** [comment]
I'll create the DLL on my other laptop with Visual Studio 2015 so no problem :P But it's'handy for people who can't build the DLL

**Comment by Alexlander** [comment]
I created the WebRTC.Net.DLL and put it in my existing project but now it's missing ManagedConductor. Must I put something else with it?

**Comment by radioman** [comment]
check the demo dude

**Comment by Alexlander** [comment]
Ah it uses WebRTCNative lol, apparently just cloned the master branch 😆
