### ISSUE TITLE
"Access Violation" on PushFrame

### ISSUE THREAD

**Issue by Alexlander** [radioman/WebRtc.NET#55]
The datachannels luckily do work, currently just sending Base64 screengrabs over it lol. It works ok but not great. 
I seem to do everything in order. It just sends it to 1 stream etc, don't see anything weird. 

I just do this in the browser
```
 remotestream.onaddstream = function(e) {
        try {
            console.log("remote media connection success!");

            var screenRTC = document.getElementById('screenrtc');
            screenRTC.srcObject = e.stream;
            screenRTC.onloadedmetadata = function(e) {
                screenRTC.play();
            };
```

And this in the C# timer

`				foreach (var s in WebRTCServer.Streams)
				{
					s.Value.WebRtc.CaptureFrameAndPush();
return;
}`

**Comment by radioman** [comment]
did you build with capture enabled?

**Comment by Alexlander** [comment]
.PushFrame() with the master DLL does work (with a green screen lol). Although if I try it with the staging DLL I get: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. with
 `					var pinned = GCHandle.Alloc(stream.ToArray(), GCHandleType.Pinned);
					IntPtr address = pinned.AddrOfPinnedObject();
	
					s.Value.WebRtc.PushFrame(address);
					pinned.Free();`
stream comes from a bitmap of the screen (so CaptureFrameAndPush is unnecessary)

**Comment by Alexlander** [comment]
Compiled a 32-bit dll and its still not working sadly, don't know why :(

**Comment by Alexlander** [comment]
With a 64-bit dll I get The program '[41576] example.vshost.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

**Comment by Alexlander** [comment]
Should I open a new issue?

**Comment by Alexlander** [comment]
I'll recompile everything, right now I get `Unhandled exception at 0x00007FFC7B30C1D9 (WebRtcNative.dll) in .exe.: 0xC0000005: Access violation reading location 0x000000FEF3A8E000.`

**Comment by Alexlander** [comment]
Still gives me the error, tried different ways of using Pointers too, don't know what else it can be.

Tried
`					BitmapData bmdata = curGrab.LockBits(new Rectangle(0, 0, curGrab.Width, curGrab.Height), System.Drawing.Imaging.ImageLockMode.ReadWrite, curGrab.PixelFormat);		
			
					unsafe
					{
						IntPtr ptr = bmdata.Scan0;
							s.Value.WebRtc.PushFrame(ptr);
					}
`

**Comment by Alexlander** [comment]
The error happens in concuctor.cc at line 533

`if (jpegc)
r = tjEncodeYUV3(jpegc, img, width_, pitch, height_, pxFormat, yuv, pad, TJSAMP_420, true ? TJFLAG_FASTDCT : TJFLAG_ACCURATEDCT);`

It seems to be fine, other than img contains a hex digit 0x000..... with a lot of "\x14\"

**Comment by Alexlander** [comment]
Implemented the example code in my app, didn't work. Also tried to implement my code in the example, also didn't work (no access violation error, just a blackscreen). The unedited example does work, not the captureframepush though. 

My captureframe can change in size, maybe that's the problem...

**Comment by radioman** [comment]
probably

**Comment by Alexlander** [comment]
Yeah that's the problem. Just need to make sure the allocated byte is made out of const variables. 

Just going to always have the screen run at 1080p and scale if the image is smaller or bigger.

**Comment by Cozdemir** [comment]
Could you please give detail how did you solve this problem ?  I'm getting excepiton when my screen resolution is 1918x888 but if i change resoulution to **1920**x888 it works fine. What's the logic behind this. How can i select correct resolution combination

**Comment by Cozdemir** [comment]
Thank you so much for your reply.  You mean for example when i want to connect to remote client first i should set resolution to something that i know it works for example ( 1024x512) then i capture screen with this resolution. This is my final solution. For now i'm trying to find automatic solution. first i check user's resolution if both height and width can be divisible by 4 i use that resolution if not i increase each by one untill both can be divisible by 4.

Yes this assumes every resolution can be divisible by 4 works. ( for my tests it does but ofcorse i will do more wider tests in different clients ) after that if it doesn't work i will switch back to your method. (if i understood you method correctly)
