### ISSUE TITLE
WinForms Viewer

### ISSUE THREAD

**Issue by royben** [radioman/WebRtc.NET#56]
Hi, great project!

How would I go about creating a WinForms project that will act only as a viewer of the WebRTC Demo included in the solution? Is that possible?

Thanks,

**Comment by radioman** [comment]
well the demo is the 'viewer'

**Comment by royben** [comment]
Yes, I understand the demo can view video and audio stream from a web client. But, what if I would like to create a WinForms client that will act like the web client. Meaning, have a "Connect" button, then start receiving video/audio from the server demo.

**Comment by radioman** [comment]
you can do that too

**Comment by royben** [comment]
If you could describe the steps to accomplish that it would be very helpful. Thanks.
