### ISSUE TITLE
CaptureFrameBGRX return IntPtr.Zero

### ISSUE THREAD

**Issue by EbramSamy** [radioman/WebRtc.NET#57]
from staging branch : 
I enabled Desktop Capture:
#define DESKTOP_CAPTURE 1
but CaptureFrameBGRX return IntPtr.Zero all the time
WebRtc.CaptureFrameBGRX(ref x, ref y) 

it worked for me before but now it is not working. and it works fine from the master branch

**Comment by EbramSamy** [comment]
@radioman  also the last version of staging branch working fine 
at this commit:  https://github.com/radioman/WebRtc.NET/commit/9afe865b03e41faaa6aecf90ff200a413ee487b7

**Comment by EbramSamy** [comment]
I tested and I found that the issue is in that commit 
https://github.com/radioman/WebRtc.NET/commit/518be1a3b28748e494d34877cde0f0a96714bcc6 
anycpu Support

**Comment by radioman** [comment]
you probably have cached some old/temp version, after any change for native dll you have to increase version number at https://github.com/radioman/WebRtc.NET/blob/staging/WebRtc.NET/WebRtcNative.cs#L13 or clear user temp dir
