### ISSUE TITLE
WebRtc.NET.Demo.exe Can not open .

### ISSUE THREAD

**Issue by MrsZ** [radioman/WebRtc.NET#58]
I build the project in vs2015 without  any errors,  but when i run this , There was an exception in the Application.Run(new MainForm());      
 static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());   （exception） 
        }

How can i solve thie problem？ thanks。

**Comment by radioman** [comment]
forks for me
