### ISSUE TITLE
Creating a local stream to app

### ISSUE THREAD

**Issue by km147** [radioman/WebRtc.NET#6]
Noticed from the rtc_main.js (webpage) that there's the ability to send local video stream to the c# code:

 if (localstream) {
     remotestream.addStream(localstream);
 }

I would like to know whether its possible to use your library to display the local stream on the MainForm within the app? (in other words broadcasting from the page to the app).

Very much appreciate your kind reply.
Shawn

**Comment by radioman** [comment]
yes it possible, but not implemented for the demo yet

check [conductor.cc](https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/src/conductor.cc) void Conductor::OnAddStream(webrtc::MediaStreamInterface* stream) { ...

basically you get track and start rendering it

**Comment by km147** [comment]
We are still looking very closely at this. Would you be so kind as to provide the code that enables us to render the stream within the C# app

**Comment by radioman** [comment]
you need to check official webrtc example and try to add required functions, thats my plan anyway

**Comment by radioman** [comment]
p.s. works just fine!
