### ISSUE TITLE
'Failed to load: ' error in WebRTCNative.cs

### ISSUE THREAD

**Issue by Alexlander** [radioman/WebRtc.NET#63]
The DLL exists, but it can't load it from my temp file location, also recreated it. Didn't run it for a few weeks and now I have it. What can the cause be? Thanks!

**Comment by radioman** [comment]
dunno, try clear temp dir

**Comment by Alexlander** [comment]
No luck, I'll try to rebuild WebRTC

**Comment by Alexlander** [comment]
Also rebuilded, maybe some permission changed in my windows

**Comment by Alexlander** [comment]
It builded a wrong dll, think the temp file got deleted, just changed some code and undo it and now it works lol weird
