### ISSUE TITLE
Execution environment

### ISSUE THREAD

**Issue by yantaka718** [radioman/WebRtc.NET#9]
Hi!

I tried your code on several environment. It worked on only Windows10, and
it doesn't work on Windows7, 8. (I would like to use WebRTC on Windows 8)
I use Visual Studio 2015 professional on all environment. Please let me
know your environment.

Could you kindly advise me if you have any limitation on your code?

**Comment by radioman** [comment]
there is no limitation, you have to distribute crt dlls: 

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\
or C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.CRT\

**Comment by radioman** [comment]
p.s. try latest version, crt dlls included
